# manifests/19-hpa-front.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: # A rellenar por el estudiantado
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: # A rellenar por el estudiantado
  minReplicas: # A rellenar por el estudiantado
  maxReplicas: # A rellenar por el estudiantado
  metrics:
  - type: Resource
    resource:
      name: # A rellenar por el estudiantado
      target:
        type: # A rellenar por el estudiantado
        averageUtilization: # A rellenar por el estudiantado
