# manifests/19-hpa-front.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: p4-ti-grupo8-hpa # A rellenar por el estudiantado
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ti-p3-grupo8-front #  A rellenar por el estudiantado
  minReplicas: 1 # A rellenar por el estudiantado
  maxReplicas: 5 # A rellenar por el estudiantado
  metrics:
  - type: Resource
    resource:
      name: cpu # A rellenar por el estudiantado
      target:
        type: Utilization # A rellenar por el estudiantado
        averageUtilization: 50 # A rellenar por el estudiantado


