FROM nginx:alpine
#LABEL org.opencontainers.image.source=https://github.com/TecInternet-MUIT-UAH/P3-TI-FrontEnd
COPY index.html /usr/share/nginx/html/index.html

RUN apk add --no-cache curl \
    nano
